name: enzo
description: All In One Library Ai.
version: 0.0.0
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  github: ^9.7.0
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  galaxeus_lib: ^0.0.34
  web_scraper: ^0.1.4
